name: samsung-mobile-recommendation-system
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - joblib
  - pip
  - pip:
      - python-dotenv
      - chromadb
      - ollama
